/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as HostsRouteImport } from './routes/hosts'
import { Route as ListenRouteImport } from './routes/listen'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as EpisodesIndexRouteImport } from './routes/episodes.index'
import { Route as EpisodesSlugRouteImport } from './routes/episodes.$slug'
import { Route as PodcastIndexRouteImport } from './routes/podcast.index'
import { Route as PodcastSlugRouteImport } from './routes/podcast.$slug'
import { Route as ApiAlertsRunRouteImport } from './routes/api/alerts/run'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsRoute = HostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenRoute = ListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesIndexRoute = EpisodesIndexRouteImport.update({
  id: '/episodes/',
  path: '/episodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesSlugRoute = EpisodesSlugRouteImport.update({
  id: '/episodes/$slug',
  path: '/episodes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastIndexRoute = PodcastIndexRouteImport.update({
  id: '/podcast/',
  path: '/podcast/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastSlugRoute = PodcastSlugRouteImport.update({
  id: '/podcast/$slug',
  path: '/podcast/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsRunRoute = ApiAlertsRunRouteImport.update({
  id: '/api/alerts/run',
  path: '/api/alerts/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/hosts': typeof HostsRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/story': typeof StoryRoute
  '/subscribe': typeof SubscribeRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/episodes/': typeof EpisodesIndexRoute
  '/podcast/': typeof PodcastIndexRoute
  '/api/alerts/run': typeof ApiAlertsRunRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/hosts': typeof HostsRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/story': typeof StoryRoute
  '/subscribe': typeof SubscribeRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/episodes': typeof EpisodesIndexRoute
  '/podcast': typeof PodcastIndexRoute
  '/api/alerts/run': typeof ApiAlertsRunRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/hosts': typeof HostsRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/merch': typeof MerchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/story': typeof StoryRoute
  '/subscribe': typeof SubscribeRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/episodes/': typeof EpisodesIndexRoute
  '/podcast/': typeof PodcastIndexRoute
  '/api/alerts/run': typeof ApiAlertsRunRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/hosts'
    | '/listen'
    | '/login'
    | '/merch'
    | '/reset-password'
    | '/story'
    | '/subscribe'
    | '/episodes/$slug'
    | '/podcast/$slug'
    | '/episodes/'
    | '/podcast/'
    | '/api/alerts/run'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/hosts'
    | '/listen'
    | '/login'
    | '/merch'
    | '/reset-password'
    | '/story'
    | '/subscribe'
    | '/episodes/$slug'
    | '/podcast/$slug'
    | '/episodes'
    | '/podcast'
    | '/api/alerts/run'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/hosts'
    | '/listen'
    | '/login'
    | '/merch'
    | '/reset-password'
    | '/story'
    | '/subscribe'
    | '/episodes/$slug'
    | '/podcast/$slug'
    | '/episodes/'
    | '/podcast/'
    | '/api/alerts/run'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  HostsRoute: typeof HostsRoute
  ListenRoute: typeof ListenRoute
  LoginRoute: typeof LoginRoute
  MerchRoute: typeof MerchRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StoryRoute: typeof StoryRoute
  SubscribeRoute: typeof SubscribeRoute
  EpisodesSlugRoute: typeof EpisodesSlugRoute
  PodcastSlugRoute: typeof PodcastSlugRoute
  EpisodesIndexRoute: typeof EpisodesIndexRoute
  PodcastIndexRoute: typeof PodcastIndexRoute
  ApiAlertsRunRoute: typeof ApiAlertsRunRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts': {
      id: '/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof HostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen': {
      id: '/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof ListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/': {
      id: '/episodes/'
      path: '/episodes'
      fullPath: '/episodes/'
      preLoaderRoute: typeof EpisodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/$slug': {
      id: '/episodes/$slug'
      path: '/episodes/$slug'
      fullPath: '/episodes/$slug'
      preLoaderRoute: typeof EpisodesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast/': {
      id: '/podcast/'
      path: '/podcast'
      fullPath: '/podcast/'
      preLoaderRoute: typeof PodcastIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast/$slug': {
      id: '/podcast/$slug'
      path: '/podcast/$slug'
      fullPath: '/podcast/$slug'
      preLoaderRoute: typeof PodcastSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts/run': {
      id: '/api/alerts/run'
      path: '/api/alerts/run'
      fullPath: '/api/alerts/run'
      preLoaderRoute: typeof ApiAlertsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  HostsRoute: HostsRoute,
  ListenRoute: ListenRoute,
  LoginRoute: LoginRoute,
  MerchRoute: MerchRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StoryRoute: StoryRoute,
  SubscribeRoute: SubscribeRoute,
  EpisodesSlugRoute: EpisodesSlugRoute,
  PodcastSlugRoute: PodcastSlugRoute,
  EpisodesIndexRoute: EpisodesIndexRoute,
  PodcastIndexRoute: PodcastIndexRoute,
  ApiAlertsRunRoute: ApiAlertsRunRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
