/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostsRouteImport } from './routes/hosts'
import { Route as ListenRouteImport } from './routes/listen'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as ComicIndexRouteImport } from './routes/comic.index'
import { Route as ComicWhatIAmRouteImport } from './routes/comic.what-i-am'
import { Route as EpisodesIndexRouteImport } from './routes/episodes.index'
import { Route as EpisodesSlugRouteImport } from './routes/episodes.$slug'
import { Route as PodcastIndexRouteImport } from './routes/podcast.index'
import { Route as PodcastSlugRouteImport } from './routes/podcast.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsRoute = HostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenRoute = ListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ComicIndexRoute = ComicIndexRouteImport.update({
  id: '/comic/',
  path: '/comic/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComicWhatIAmRoute = ComicWhatIAmRouteImport.update({
  id: '/comic/what-i-am',
  path: '/comic/what-i-am',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesIndexRoute = EpisodesIndexRouteImport.update({
  id: '/episodes/',
  path: '/episodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesSlugRoute = EpisodesSlugRouteImport.update({
  id: '/episodes/$slug',
  path: '/episodes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastIndexRoute = PodcastIndexRouteImport.update({
  id: '/podcast/',
  path: '/podcast/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastSlugRoute = PodcastSlugRouteImport.update({
  id: '/podcast/$slug',
  path: '/podcast/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hosts': typeof HostsRoute
  '/listen': typeof ListenRoute
  '/story': typeof StoryRoute
  '/subscribe': typeof SubscribeRoute
  '/comic/what-i-am': typeof ComicWhatIAmRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/comic/': typeof ComicIndexRoute
  '/episodes/': typeof EpisodesIndexRoute
  '/podcast/': typeof PodcastIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hosts': typeof HostsRoute
  '/listen': typeof ListenRoute
  '/story': typeof StoryRoute
  '/subscribe': typeof SubscribeRoute
  '/comic/what-i-am': typeof ComicWhatIAmRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/comic': typeof ComicIndexRoute
  '/episodes': typeof EpisodesIndexRoute
  '/podcast': typeof PodcastIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hosts': typeof HostsRoute
  '/listen': typeof ListenRoute
  '/story': typeof StoryRoute
  '/subscribe': typeof SubscribeRoute
  '/comic/what-i-am': typeof ComicWhatIAmRoute
  '/episodes/$slug': typeof EpisodesSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/comic/': typeof ComicIndexRoute
  '/episodes/': typeof EpisodesIndexRoute
  '/podcast/': typeof PodcastIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hosts'
    | '/listen'
    | '/story'
    | '/subscribe'
    | '/comic/what-i-am'
    | '/episodes/$slug'
    | '/podcast/$slug'
    | '/comic/'
    | '/episodes/'
    | '/podcast/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hosts'
    | '/listen'
    | '/story'
    | '/subscribe'
    | '/comic/what-i-am'
    | '/episodes/$slug'
    | '/podcast/$slug'
    | '/comic'
    | '/episodes'
    | '/podcast'
  id:
    | '__root__'
    | '/'
    | '/hosts'
    | '/listen'
    | '/story'
    | '/subscribe'
    | '/comic/what-i-am'
    | '/episodes/$slug'
    | '/podcast/$slug'
    | '/comic/'
    | '/episodes/'
    | '/podcast/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostsRoute: typeof HostsRoute
  ListenRoute: typeof ListenRoute
  StoryRoute: typeof StoryRoute
  SubscribeRoute: typeof SubscribeRoute
  ComicWhatIAmRoute: typeof ComicWhatIAmRoute
  EpisodesSlugRoute: typeof EpisodesSlugRoute
  PodcastSlugRoute: typeof PodcastSlugRoute
  ComicIndexRoute: typeof ComicIndexRoute
  EpisodesIndexRoute: typeof EpisodesIndexRoute
  PodcastIndexRoute: typeof PodcastIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts': {
      id: '/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof HostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen': {
      id: '/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof ListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comic/': {
      id: '/comic/'
      path: '/comic'
      fullPath: '/comic/'
      preLoaderRoute: typeof ComicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comic/what-i-am': {
      id: '/comic/what-i-am'
      path: '/comic/what-i-am'
      fullPath: '/comic/what-i-am'
      preLoaderRoute: typeof ComicWhatIAmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/': {
      id: '/episodes/'
      path: '/episodes'
      fullPath: '/episodes/'
      preLoaderRoute: typeof EpisodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/$slug': {
      id: '/episodes/$slug'
      path: '/episodes/$slug'
      fullPath: '/episodes/$slug'
      preLoaderRoute: typeof EpisodesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast/': {
      id: '/podcast/'
      path: '/podcast'
      fullPath: '/podcast/'
      preLoaderRoute: typeof PodcastIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast/$slug': {
      id: '/podcast/$slug'
      path: '/podcast/$slug'
      fullPath: '/podcast/$slug'
      preLoaderRoute: typeof PodcastSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostsRoute: HostsRoute,
  ListenRoute: ListenRoute,
  StoryRoute: StoryRoute,
  SubscribeRoute: SubscribeRoute,
  ComicWhatIAmRoute: ComicWhatIAmRoute,
  EpisodesSlugRoute: EpisodesSlugRoute,
  PodcastSlugRoute: PodcastSlugRoute,
  ComicIndexRoute: ComicIndexRoute,
  EpisodesIndexRoute: EpisodesIndexRoute,
  PodcastIndexRoute: PodcastIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
